name: compatible_animation
version: 0.5.24
description: Compatible port of the Kai Sellgren's original animation library.
author: Daniel Varga <dvargahali@gmail.com>
homepage: https://github.com/daniel-v/Animation
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  browser: any
dev_dependencies:
  unittest: '>=0.9.0 < 0.10.0'
